version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGPORT: 5433
    networks:
      - worldstage-net

  nginx-rtmp:
    build:
      context: ../backend/nginx-rtmp
      dockerfile: Dockerfile
    platform: linux/arm64
    ports:
      - "1935:1935"  # RTMP ingest
      - "8080:8080"  # HLS output
    environment:
      API_HOST: spring-boot:8082
      HLS_OUTPUT_DIR: /mnt/hls
    volumes:
      - ./hls-data:/mnt/hls
    networks:
      - worldstage-net
    depends_on:
      - spring-boot
    user: root

  spring-boot:
    build:
      context: ../backend/worldstage-api
      dockerfile: Dockerfile.local
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - worldstage-net
    depends_on:
      - db

  ffmpeg-worker:
    build:
      context: ../backend/encoder-worker
    container_name: transcoder-worker
    ports:
      - "3001:3001"
    volumes:
      - ./hls-data:/mnt/hls
    networks:
      - worldstage-net
    user: root  # Update for prod

networks:
  worldstage-net:
    driver: bridge
