version: '3.8'

services:
  db:
    container_name: db
    image: postgres
    ports:
      - "5433:5433"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      PGPORT: 5433
    networks:
      - worldstage-net

  nginx-rtmp:
    image: tiangolo/nginx-rtmp:latest
    platform: linux/arm64
    ports:
      - "1935:1935" # RTMP ingest (OBS)
      - "8080:8080" # HLS delivery
    volumes:
      - ./hls-data:/var/hls
      - ../backend/nginx-rtmp/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - worldstage-net
    depends_on:
      - spring-boot
    user: root  # Update for prod

  spring-boot:
    build:
      context: ../backend/worldstage-api
    ports:
      - "8082:8082"
    environment:
      SPRING_PROFILES_ACTIVE: docker
    networks:
      - worldstage-net
    depends_on:
      - db

  ffmpeg-worker:
    build:
      context: ../backend/encoder-worker
    container_name: transcoder-worker
    ports:
      - "3001:3001"
    volumes:
      - ./hls-data:/var/hls
    networks:
      - worldstage-net
    user: root  # Update for prod

networks:
  worldstage-net:
    driver: bridge
